### ISSUE TITLE
スレッドロケーション

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#126]
どこだっけね？
スレッド番号をキーにして何かをMapで保存して、ユーザ毎に何かを管理してなかったかしらね？

それと同等のことをやってくれる『ThreadLocation』なるものがあるらしいのね。
石野さんも先日、初めて知ったのよね。
今のプロジェクトでね。
自前でやるより、コレ使ったほうがいいよね。

でもね、Webで使うときは注意が必要らしいのよね。
以下参照ね。
http://d.hatena.ne.jp/yamadamn/20131214/1386996898

**Comment by fukumotom** [comment]
Commondbutils#openConnection　で使用しているので、対応します。

**Comment by btishinoyu** [comment]
おｋ。
