### ISSUE TITLE
resultSetの存在するカラムをDtoに詰める処理を完成させる。

### ISSUE THREAD

**Issue by btkigamim** [fukumotom/WorkManager#28]
private static ArrayList<WorkDto> resultSetToWorkDtoList(ResultSet result)
			throws SQLException {

		String regex = "_[a-z]";
		Pattern ptm = Pattern.compile(regex);

		HashMap<String, String> clmNameMap = new HashMap<String, String>();
		ResultSetMetaData meta = result.getMetaData();
		for (int i = 1; i < meta.getColumnCount() + 1; i++) {

			meta.getColumnType(i);
			clmNameMap.put(meta.getColumnClassName(i), meta.getColumnLabel(i));
		}

		ArrayList<WorkDto> dtoList = new ArrayList<>();
		// Method[] dtoMethods = new WorkDto().getClass().getMethods();
		HashMap<String, String> setterTypeMap = new HashMap<String, String>();
		for (Entry<String, String> entry : clmNameMap.entrySet()) {
			String clmNm = entry.getValue();
			logger.info("clmNameMap内容[型]:ラベル     [{}]:{}", entry.getKey(),
					clmNm);

			// ラベル名からフィールド名へ変換
			Matcher mat = ptm.matcher(clmNm);
			String fldNm = null;
			if (mat.find()) {
				fldNm = clmNm.replace(mat.group(), mat.group().substring(1)
						.toUpperCase());
				logger.info("フィールド名:{}", fldNm);
			}
			String setter = "set" + fldNm.substring(0, 1).toUpperCase()
					+ fldNm.substring(1);
			logger.info("setter:{}", setter);
			clmNameMap.replace(entry.getKey(), setter);

		}
		for (Entry<String, String> entry : clmNameMap.entrySet()) {
			logger.info("clmNameMap内容[型]:setter     [{}]:{}", entry.getKey(),
					entry.getValue());
		}

		// Object obj;
		// try {
		// obj = Class.forName(entry.getValue()).getClass();
		// } catch (ClassNotFoundException e) {
		// logger.error("DBから取得した値の変換に失敗しました。");
		// throw new SystemException(e);
		// }
		while (result.next()) {
			WorkDto dto = new WorkDto();

			// if (obj instanceof String) {
			//
			// }

			dto.setId((result.getInt("id")));
			dto.setStartTime(result.getTime("start_time"));
			dto.setEndTime(result.getTime("end_time"));
			dto.setWorkingTime(result.getTime("working_time"));
			dto.setContents(result.getString("contents"));
			dto.setNote(result.getString("note"));
			dtoList.add(dto);
		}

		return dtoList;
	}

**Comment by fukumotom** [comment]
#85 で再整理するためクローズ。
