### ISSUE TITLE
SonarQube エラー

### ISSUE THREAD

**Issue by btkigamim** [fukumotom/WorkManager#29]
BindFormatException
フィールドをfinalに設定

ConvertToModelUtils
コンストラクタ　隠ぺい
　convertBoolean()
　・パラメータ不要
　・return 文に式を設定

DateUtils
コンストラクタ隠ぺい

MsgCodeDef
コンストラクタの上にメンバの宣言

WorkDao
　findAllWork()
 runtimeException（システムエラー）はthrows不要

CommonDbUtil.java 
　insertUsers()
　findWorking()
  findWorking()
  startWork()
 findAllWork()
  ほか
  引数の実装クラスを隠ぺい

**Comment by fukumotom** [comment]
対応済み。クローズ。
