### ISSUE TITLE
テーブル表示と挿入機能を追加

### ISSUE THREAD

**Issue by btkigamim** [fukumotom/WorkManager#4]
データ挿入の以下のカラムを追加、修正
・updateFlg
・insertFlg
・content → contents
SQLファイル読み込み時に改行を入れる。
発行するSQLをログ出力する。
SQLを追加。
　・全件取得
　・選択行の開始時間取得
　・インサート
画面の再表示にリダイレクトを使用する。
　→サンプルクラスを削除。

**Comment by fukumotom** [comment]
データ挿入のカラム追加　完了
SQLファイル読み込み時の改行修正　完了
発行SQLのログ出力実装　完了
SQL
　・全件取得　を追加

**Comment by fukumotom** [comment]
作業の挿入機能を実装済み。クローズ。
