### ISSUE TITLE
GitからEclipseの設定ファイルの除去

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#42]
Eclipseの設定ファイルをGitに登録してるじゃないか！
 .settings
 .classpath
 .project

**Comment by btishinoyu** [comment]
.settings消しなさいよ。

**Comment by fukumotom** [comment]
修正しました。
[PR](https://github.com/fukumotom/WorkManager/pull/93)しました。

**Comment by btishinoyu** [comment]
ok
