### ISSUE TITLE
inputタグを閉める

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#49]
workList.jsp のinputタグ。
開けたらしめなさいよぉ！
横の文字（削除を含む とか (yyyy/MM/dd) とか） が Inputタグのデータと勘違いされて警告でてるじゃないか！

**Comment by btkigamim** [comment]
[PR](https://github.com/fukumotom/WorkManager/pull/60)
で対応しました。

**Comment by btishinoyu** [comment]
OK。
