### ISSUE TITLE
例外処理の再検討

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#50]
`jp.kigami.ojt.servlet.WorkRegister.doPost(HttpServletRequest,` HttpServletResponse)
で、
`request.getParameter("id");`
が空文字の場合（NULLの場合も）、どうするの？
例外じゃない？

というか、から文字判定に
`id` != ""
は無い！
`id.isEmpty()`
を使いなさいよ！

**Comment by btkigamim** [comment]
空文字チェックを修正しました。
[PR](https://github.com/fukumotom/WorkManager/pull/62)

**Comment by btishinoyu** [comment]
idがnullの時、例外発生する！
NGだ！やりなおし！

**Comment by btkigamim** [comment]
nullチェック対応は以下のPRのコメントで対応します。
[PR](https://github.com/fukumotom/WorkManager/pull/61) NULL考慮

PR統合のため、古いほうのPRをクローズして#issue50ブランチを削除します。
[古いPR](https://github.com/fukumotom/WorkManager/pull/62)
