### ISSUE TITLE
直値から定数への置き換え

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#51]
WorkRegister.javaの
"作業終了" とか "作業開始" とか
直値をやめなさい。定数使いなさい。

画面で付けた（HTML側の）名前である
`request.getParameter("contents");` の "contents"
とかはいいや。
あ、でも、ロジック側で命名して使いまわす
`request.getParameter("state");` の "state"
とかは許さん。

↓を一読して、自分なりの（他人を説得せしめるほど確かな）ルールを作りなさいな。
http://itpro.nikkeibp.co.jp/article/COLUMN/20070820/279836/?rt=nocnt
http://blogs.wankuma.com/shuujin/archive/2007/04/19/72007.aspx

**Comment by btkigamim** [comment]
[PR](https://github.com/fukumotom/WorkManager/pull/61)で対応しました。

**Comment by fukumotom** [comment]
定数定義クラスの作成をまとめました。
こちらを確認してください。
[PR](https://github.com/fukumotom/WorkManager/pull/73)
