### ISSUE TITLE
WorkRegister.doPost の処理見直し

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#53]
jp.kigami.ojt.servlet.WorkRegister.doPost(HttpServletRequest, HttpServletResponse)
作業開始のルートで、
状態が作業中 の場合に、
workFinishでBusinessExceptionが発生した時、
workFinishは失敗したくせに、続きの新規作業の登録の処理が普通に行われちゃうのだけど。
DBの整合性が崩れない？

ていうか、doPost内でdoGetメソッド呼ぶとは何事か！？草はえる！

**Comment by fukumotom** [comment]
doGetの呼び出しを修正しました。
[PR](https://github.com/fukumotom/WorkManager/pull/66)

**Comment by fukumotom** [comment]
石野さんissue対応ブランチマージ済み。
確認してクローズする。
