### ISSUE TITLE
workRegistForm.jsp の 不思議なリクエスト属性の使い方の改善

### ISSUE THREAD

**Issue by btishinoyu** [fukumotom/WorkManager#54]
workRegistForm.jsp で
`request.setAttribute("now",` now);
ってやってるけども…
これ、
jp.kigami.ojt.servlet.WorkRegister.doGet(HttpServletRequest, HttpServletResponse)
でやるべきことじゃない？
というか、Work を用意してるんだから、Workにぶち込んどくもんじゃない？

あと、"stateStr"属性をJSPで作ってるけど、これなんで？
jp.kigami.ojt.servlet.WorkRegister.doGet(HttpServletRequest, HttpServletResponse)
でやるべきことじゃない？
それにhiddenタグに"stateStr"属性の値を格納してるけど、
フォワードしてるんだから、リクエスト情報は引き継げるでしょ？
要らなくない？
いや、それ以前に"stateStr"属性の値って、DB状態を指してるよね！？
リクエストまたいでDB状態を参照して処理をするってどうなの！？
って前、話した！

んん？
というか、workRegistForm.jspに
`````
if ("working".equals(state))
…
Object obj = request.getAttribute("working");
…
    work = (Work) obj;
    request.setAttribute("work", work);
`````
って処理あるけど…"working"が複数ある！混乱するわ！
そもそもなぜにWorkのオブジェクトを"working"属性から"work"属性に入れ替えた！？
混乱するわ！混乱するわ！ぎゃー！

**Comment by btkigamim** [comment]
[PR](https://github.com/fukumotom/WorkManager/pull/61)で対応しました。

**Comment by btishinoyu** [comment]
ひとまずOK。
